name: CI/CD Node.js Pipeline

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main", "workflow" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   

      - name: Install dependencies
        run: npm install

      - name: Run Tests (Karma + Jasmine)
        run: npx karma start --single-run

      - name: Run ESLint
        run: npx eslint . --fix

      - name: Run Snyk (Security Scan)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: npx snyk test || echo "Snyk encontro vulnerabilidades, continuando flujo."

      - name: Install Sonar Scanner
        run: npm install -g sonar-scanner
          